config/routes.rb
Rails.application.routes.draw do
  resources :reservations, only: [] do
    resources :payments, only: [:new, :create]
  end
  
  resources :listings do
    resources :reservations, only: [:create, :show]
  end

  resources :users, only: [:show, :edit, :update, :destroy] 
  
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  post "/listings/filter" => "listings/filter", as: "filter"
  post "/listings/search" => "listings#search", as: "search"
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  root 'welcome#index'

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	
	belongs_to :user
	has_many :reservations
	mount_uploaders :photos, PhotosUploader

	include PgSearch
	pg_search_scope :search_by_address, :against => :address
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def new
  	@listing = Listing.new
  	render template: "listings/new"
  end

  def create
  	@listing = current_user.listings.new(listing_params)
  	if @listing.save
			redirect_to '/listings'
    else
        render 'new'
    end
	end

	def index
		@user = current_user
		if @user.role == "landlord"
			@listings = Listing.where(user_id: current_user.id).paginate(:page => params[:page], :per_page => 5)
		else 
			@listings = Listing.all.paginate(:page => params[:page], :per_page => 5).order('name DESC')
		end
		render template: "listings/index"
	end

	def show
		@listing = Listing.find(params[:id])
		@user = @listing.user
		render template: "listings/show"
	end

	def edit
		@listing = Listing.find(params[:id])
		render template: "listings/edit"
	end

	def update
		@listing = Listing.find(params[:id])
		if @listing.update(listing_params)
			redirect_to "/listings/#{@listing.id}", notice: "Success!"
		else 
      render 'edit'
    end
	end

	def destroy
		Listing.destroy(params[:id])
		redirect_to "/listings"
	end

	def search
		@listings = Listing.search_by_address(params[:search])
		render template: "listings/search"
	end

	def filter
		results = self.where("MIN(price, sale_price) >= :min AND MIN(price, sale_price) <= :max", min: min, max: max)
	end

	private

	def listing_params
		params.require(:listing).permit(:name, :description, :address, :price, {photos: []})
	end
end

app/helpers/listing_helper.rb
module ListingHelper
end

app/views/listings/_form.html.erb
<%= form_for @listing do |form| %>
  <div class="text-field">
    <%= form.label :name %>
    <%= form.text_field :name, type: 'name' %>
  </div>

  <div class="text-field">
    <%= form.label :description %>
    <%= form.text_field :description, type: 'description' %>
  </div>

  <div class="text-field">
    <%= form.label :address %>
    <%= form.text_field :address, type: 'address' %>
  </div>

  <div class="text-field">
    <%= form.label :price %>
    <%= form.text_field :price, type: 'price' %>
  </div>
  <%= form.file_field :photos, multiple: true %>

  <div class="submit-field">
    <%= form.submit "Submit" %>
  </div>
<% end %>

app/views/listings/edit.erb
<%= form_for @listing do |form| %>
	<%= hidden_field_tag("_method", "patch") %>
	<h4>Name</h4><input type='text' placeholder="Name of property" name="listing[name]" value= "<%= @listing.name %>"><br>
	<h4>Description</h4><input type='text' placeholder="Description of Property" name="listing[description]" value= "<%= @listing.description %>"><br>
	<h4>Address</h4><input type='text' placeholder="Address of property" name="listing[address]" value= "<%= @listing.address %>"><br>
	<h4>Price</h4><input type='text' placeholder="Price of property" name="listing[price]" value= "<%= @listing.price %>"><br>
	<input type='submit' value="Submit">
	<a href="/listings/<%= @listing.id %>"><button>Cancel</button></a>
<% end %>

app/views/listings/index.erb
<h1>All My Listings</h1>

<% if @user.role == "superadmin" || @user.role == "landlord" %>
	<%= link_to "Add New Listing", new_listing_path %>
<% end %>

			
<% @listings.each do |listing| %>
	<% if current_user.id == listing.user_id %>
		<% if listing.reservations.any? %>
			<table>
			  <thead>
			    <tr>
			      <th>Name</th>
			      <th>Description</th>
			      <th>Address</th>
			      <th>Price</th>
			      <th colspan="12"></th>
			    </tr>
			  </thead>
			  <tbody>
					<tr>
						<td><a href="/listings/<%= listing.id %>"><%= listing.name %></a></td>
						<td><%= listing.description %></td>
						<td><%= listing.address %></td>
						<td><%= listing.price %></td>
					</tr>
				</tbody>
			</table>

			<% listing.reservations.each do |reservation| %>
				<table>
				  <thead>
				    <tr>
				      <th>Reservation ID</th>
				      <th>User ID</th>
				      <th>Check-In Date</th>
				      <th>Check-Out Date</th>
				      <th colspan="4"></th>
				    </tr>
				  </thead>

				  <tbody>
						<tr>
							<td><a href= "/listings/<%= listing.id %>/reservations/<%= reservation.id %>"><%= reservation.id %></a></td>
							<td><%= reservation.user_id %></td>
							<td><%= reservation.check_in %></td>
							<td><%= reservation.check_out %></td>
						</tr>
					</tbody>
				</table>
			<% end %>
		<% end %>
<!-- 	< % else %>
		<table>
		  <thead>
		    <tr>
		      <th>Name</th>
		      <th>Description</th>
		      <th>Address</th>
		      <th>Price</th>
		      <th colspan="4"></th>
		    </tr>
		  </thead>

		  <tbody>
				<tr>
					<td><a href="/listings/<%= listing.id %>"><%= listing.name %></a></td>
					<td><%= listing.description %></td>
					<td><%= listing.address %></td>
					<td><%= listing.price %></td>
				</tr>
			</tbody>
		</table>
	< % end %>	

 -->	<% elsif current_user.id != listing.user_id %>
		<table>
		  <thead>
		    <tr>
		      <th>Name</th>
		      <th>Description</th>
		      <th>Address</th>
		      <th>Price</th>
		      <th colspan="4"></th>
		    </tr>
		  </thead>

		  <tbody>
				<tr>
					<td><a href="/listings/<%= listing.id %>"><%= listing.name %></a></td>
					<td><%= listing.description %></td>
					<td><%= listing.address %></td>
					<td><%= listing.price %></td>
				</tr>
			</tbody>
		</table>
	<% end %>	
<% end %>	

<%= will_paginate @listings %>



      

app/views/listings/new.html.erb
<div id="listings" class="new-listing">
  <h2>New Listing</h2>

  <%= render partial: '/listings/form' %>

</div>

app/views/listings/search.erb
<h2>Results from search</h2>

<% @listings.each do |listing| %>
	<table>
	  <thead>
	    <tr>
	      <th>Name</th>
	      <th>Description</th>
	      <th>Address</th>
	      <th>Price</th>
	      <th colspan="12"></th>
	    </tr>
	  </thead>
	  <tbody>
			<tr>
				<td><a href="/listings/<%= listing.id %>"><%= listing.name %></a></td>
				<td><%= listing.description %></td>
				<td><%= listing.address %></td>
				<td><%= listing.price %></td>
			</tr>
		</tbody>
	</table>
<% end %>

app/views/listings/show.erb
<h2><%= @listing.name %></h2><br>
	<% unless @listing.photos.empty? %> 
		<% @listing.photos.each do |photo| %>
			<%= image_tag photo.thumb.url %>
		<% end %>
	<% end %>
	
<ul>	
	<li><%= @listing.description %></li><br>
	<li><%= @listing.address %></li><br>
	<li><%= @listing.price %></li>
</ul>	

<% if signed_in? & current_user.role == "superadmin" || current_user.role == "tenant" %>
	<%=  render '/reservations/form' %>
<% elsif !signed_in? %>
	<p>Please <%= link_to "Sign in", sign_in_path %> to make a reservation</p>	
<% end %>	

<% if current_user.id == @user.id %>

	<a href="/listings/<%= @listing.id %>/edit">Edit listing</a>
	
	<%= form_for @listing do |form| %>
		<%= hidden_field_tag("_method", "delete") %>
		<input type='submit' value="Delete">
	<% end %>	

<% end %>	