config/routes.rb
Rails.application.routes.draw do
  resources :reservations, only: [] do
    resources :payments, only: [:new, :create]
  end
  
  resources :listings do
    resources :reservations, only: [:create, :show]
  end

  resources :users, only: [:show, :edit, :update, :destroy] 
  
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  post "/listings/filter" => "listings/filter", as: "filter"
  post "/listings/search" => "listings#search", as: "search"
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
  include PgSearch
  
  has_many :reservations
  has_many :listings
  has_many :authentications, :dependent => :destroy

  enum role: {superadmin: 0, landlord: 1, tenant: 2}

  mount_uploader :avatar, AvatarUploader

  def self.create_with_auth_and_hash(authentication,auth_hash)
    create! do |u|
      # u.first_name = auth_hash["info"]["first_name"]
      u.email = auth_hash["extra"]["raw_info"]["email"]
      u.authentications<<(authentication)
    end
  end

  def fb_token
    x = self.authentications.where(:provider => :facebook).first
    return x.token unless x.nil?
  end

  def password_optional?
    true
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  # if respond_to?(:before_action)
  #   before_action :redirect_signed_in_users, only: [:create, :new]
  #   skip_before_action :require_login, only: [:create, :new], raise: false
  #   skip_before_action :authorize, only: [:create, :new], raise: false
  # else
  #   before_filter :redirect_signed_in_users, only: [:create, :new]
  #   skip_before_filter :require_login, only: [:create, :new], raise: false
  #   skip_before_filter :authorize, only: [:create, :new], raise: false
  # end

  def new
    @user = User.new
    render template: "users/new"
  end

  def create
    @user = User.new(user_params)

    if @user.save
       sign_in @user
      # UserMailer.welcome_email(@user).deliver_later
      render template: "users/edit"
    end
  end

  #   respond_to do |format|
  #     if @user.save
  #       sign_in @user
  #       # Tell the UserMailer to send a welcome email after save
  #      UserMailer.welcome_email(@user).deliver_later
 
  #       format.html { redirect_to(@user, notice: 'User was successfully created.') }
  #       format.json { render json: @user, status: :created, location: @user }
  #     else
  #       format.html { render action: 'new' }
  #       format.json { render json: @user.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  def show
    @user = User.find(params[:id])
    render template: "users/show"
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to "/users/#{@user.id}", notice: "Success!"
    else 
      render 'edit'
    end
  end

  private

  def avoid_sign_in
    warn "[DEPRECATION] Clearance's `avoid_sign_in` before_filter is " +
      "deprecated. Use `redirect_signed_in_users` instead. " +
      "Be sure to update any instances of `skip_before_filter :avoid_sign_in`" +
      " or `skip_before_action :avoid_sign_in` as well"
    redirect_signed_in_users
  end

  def redirect_signed_in_users
    if signed_in?
      redirect_to Clearance.configuration.redirect_url
    end
  end

  def url_after_create
    Clearance.configuration.redirect_url
  end

  def user_from_params
    email = user_params.delete(:email)
    password = user_params.delete(:password)

    Clearance.configuration.user_model.new(user_params).tap do |user|
      user.email = email
      user.password = password
    end
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :role, :avatar)
  end
end

app/views/users/_form.html.erb
<%= form_for (@user) do |form| %>
  <div class="text-field">
    <%= form.label :email %>
    <%= form.text_field :email, type: 'email' %>
  </div>

  <div class="password-field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="submit-field">
    <%= form.submit "Sign Up"%>
  </div>

<% end %>

app/views/users/edit.erb
<h2>Edit Profile</h2>
<%= form_for @user do |form| %>
	<%= hidden_field_tag("_method", "patch") %>
	<%= form.file_field :avatar %>
	<h4>First Name</h4><input type='text' placeholder="First Name" name="user[first_name]" value= "<%= @user.first_name %>"><br>
	<h4>Last Name</h4><input type='text' placeholder="Last Name" name="user[last_name]" value= '<%= @user.last_name %>'><br>
	<h4>Email</h4><input type='text' placeholder="Email" name="user[email]" value= "<%= @user.email %>"><br>
	<h4>Password</h4><input type=password placeholder="Password" name="user[password]"><br>
	<%= form.radio_button("role", "landlord") %><h4>Landlord</h4>
	<%= form.radio_button("role", "tenant") %><h4>Tenant</h4>
	<input type='submit' value="Update">
	<a href="/users/<%= @user.id %>"><button>Cancel</button></a>
<% end %>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %><br>
       <a href="/auth/facebook">Facebook Login</a>

    </div>
  <% end %>
</div>

app/views/users/show.erb
<h1>Profile</h1>

<p> Hello! Welcome to <%= @user.first_name %>'s page</p>
<%= image_tag @user.avatar.thumb.url %>

<p> Name: <%= @user.first_name %> <%= @user.last_name %></br>

<p> email: <%= @user.email %></br>

<% if current_user.id == @user.id %>

	<%= link_to 'Edit', edit_user_path(@user) %> |
	<%= link_to 'Back', users_path %>

	<a href="/users/<%= @user.id %>/delete">Delete Account</a>

<% end %>