config/routes.rb
Rails.application.routes.draw do
  resources :reservations, only: [] do
    resources :payments, only: [:new, :create]
  end
  
  resources :listings do
    resources :reservations, only: [:create, :show]
  end

  resources :users, only: [:show, :edit, :update, :destroy] 
  
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  post "/listings/filter" => "listings/filter", as: "filter"
  post "/listings/search" => "listings#search", as: "search"
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  root 'welcome#index'

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
	def new
		# byebug
		@reservation = Reservation.find(params[:reservation_id])
		gon.client_token = generate_client_token
	end

	def create
		@reservation = Reservation.find(params[:reservation_id])
		listing = @reservation.listing_id
    @result = Braintree::Transaction.sale(
	    amount: @reservation.total_price,
	    payment_method_nonce: params[:payment_method_nonce])
    @user = @reservation.user
   	host = @reservation.listing
    if @result.success?
      redirect_to listing_reservation_path(listing,@reservation.id), notice: "Congratulations! Your payment is successful!"
      @reservation.save
      ReservationMailer.booking_email(@user, host, @reservation.id).deliver_later
    else
      flash[:alert] = "Something went wrong while processing your payment. Please book again!"
      redirect_to listing_path(listing)
    end
  end



	private
	def generate_client_token
	  Braintree::ClientToken.generate
	end

end

app/views/payments/_form.html.erb
<div class="form-container radius-box glassy-bg small-10 small-centered medium-8 large-6 columns">
  <h2 class="mbs">New Payment</h2>
  <%= form_tag reservation_payments_path do %>
    <p>Please enter your payment details:</p>
    <div id="dropin"></div>
    <%=submit_tag "Pay", class: "button mt1" %>
  <%end%>
</div>
	
<script src="https://js.braintreegateway.com/v2/braintree.js"></script>

app/views/payments/new.html.erb
<div id="payments" class="new-payment">

	<h3>Total Price: $<%= @reservation.total_price %></h3>
  <%= render partial: '/payments/form' %>

</div>